# Generated by Django 6.0 on 2026-01-05 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_alter_role_name_userrole'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessrolerule',
            old_name='create_permission',
            new_name='create',
        ),
        migrations.RenameField(
            model_name='accessrolerule',
            old_name='delete_all_permission',
            new_name='delete',
        ),
        migrations.RenameField(
            model_name='accessrolerule',
            old_name='delete_permission',
            new_name='delete_all',
        ),
        migrations.RenameField(
            model_name='accessrolerule',
            old_name='read_all_permission',
            new_name='read',
        ),
        migrations.RenameField(
            model_name='accessrolerule',
            old_name='read_permission',
            new_name='read_all',
        ),
        migrations.RenameField(
            model_name='accessrolerule',
            old_name='update_all_permission',
            new_name='update',
        ),
        migrations.RenameField(
            model_name='accessrolerule',
            old_name='update_permission',
            new_name='update_all',
        ),
        migrations.AlterField(
            model_name='accessrolerule',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.role'),
        ),
    ]
